### ISSUE TITLE
class CDLL_t fails on windows with python version 3.8

### ISSUE THREAD

**Issue by esc-grs** [Zorkator/libfde#21]
When using the current master 49a55d115dad6a850f51bba0ebcc9277ffdaf3a2 trying to load `fde.2.8.0.dll` via class `CDLL_t`, loading fails for python 3.8.8, but works for python 3.7.5.

The new parameter `winmode` of `ctypes.CDLL` seems to be the cuplrit.
see https://docs.python.org/3/library/ctypes.html
> Changed in version 3.8: Added winmode parameter.

I am using the following python script `test-cdll_t.py`. Can not attach it, due to file type not supported by github. Thus as plain copy:
```
import sys
import os
# path to git clone of libfde
if len(sys.argv) < 2:
    print("Provide the path to your clone of libfde as first command line argument!")
    sys.exit(1)

pathToFDEclone = sys.argv[1]
sys.path.append(pathToFDEclone)
from fde.tools._libLoader import CDLL_t

dlltoload = os.path.join(pathToFDEclone, "_build", "package", "Release", "bin", "fde.2.8.0.dll")
try:
    fdedll = CDLL_t(dlltoload)
    print("loaded via CDLL_t", fdedll)
except:
    print("failed to load via CDLL_t:", dlltoload)
    fdedll = CDLL_t(dlltoload, winmode=0)
    print("loaded via CDLL_t with winmode=0", fdedll)
```

### Actual result
```
D:\SharedwLnx\Github>py -3.8 test-fde.py libfde
failed to load via CDLL_t: libfde\_build\package\Release\bin\fde.2.8.0.dll
loaded via CDLL_t with winmode=0 <CDLL_t 'libfde\_build\package\Release\bin\fde.2.8.0.dll', handle 7ff9a0120000 at 0x1bd2da27c40>

D:\SharedwLnx\Github>
D:\SharedwLnx\Github>py -3.7 test-fde.py libfde
loaded via CDLL_t <CDLL_t 'libfde\_build\package\Release\bin\fde.2.8.0.dll', handle 7ff9a0120000 at 0x1a503ebfb48>

D:\SharedwLnx\Github>
```

### Steps to reproduce
build `libfde` (i am using Visual Studio 2019 and Intel Fortran oneAPI 2021)
- ` git clone https://github.com/Zorkator/libfde.git`
- `cd libfde && mkdir _build && cd _build && cmake ..`
- `cmake --build . --target "fde (fde\fde)" --config Release`

run the script provided above (mind to run from Intel oneAPI command prompt to have the fortran runtime libraries in `PATH`)
- `py -3.8 test-fde.py <libfde>`
- `py -3.7 test-fde.py <libfde>`
- where `<libfde>` is the path to your libfde clone directory

### Expected behaviour
- work without `winmode` parameter as this would break linux usage and usage with python version < 3.8

**Comment by esc-grs** [comment]
One could solve this via try/except: [cdll_t-tryexcept.txt](https://github.com/Zorkator/libfde/files/6649564/cdll_t-tryexcept.txt)
Or by checking the python version: [cdll_t-testversion.txt](https://github.com/Zorkator/libfde/files/6649565/cdll_t-testversion.txt)

It would be nice, if someone could reproduce this issue

**Comment by Zorkator** [comment]
Thanks for providing the test and possible fixes!
I can reproduce this error and it seems to be an issue in python 3.8 version of ctypes.CDLL.
As given in the docs the constructor already sets the new argument winmode=0, so it should not be needed.
And in 3.9 it's just working fine again.
So I'll add the try/except fix, but using the version without passing winmode as the default, since 3.8 seems to be the odd version and I don't want to set a default value that might change in future versions of ctypes.

**Comment by esc-grs** [comment]
thanks
